package com.example.jetpackcomposethemes.ui.theme

import androidx.compose.ui.graphics.Color

//Light theme colors
// Light theme colors
val LightPrimary = Color(0xFF6200EE)
val OnLightPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBB86FC)
val OnLightPrimaryContainer = Color(0xFF000000)
val LightSecondary = Color(0xFF03DAC6)
val OnLightSecondary = Color(0xFF000000)
val LightSecondaryContainer = Color(0xFFB2DFDB)
val OnLightSecondaryContainer = Color(0xFF000000)
val LightTertiary = Color(0xFF018786)
val OnLightTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF03DAC6)
val OnLightTertiaryContainer = Color(0xFF000000)
val LightError = Color(0xFFB00020)
val OnLightError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFCF6679)
val OnLightErrorContainer = Color(0xFF000000)
val LightBackground = Color(0xFFFFFFFF)
val OnLightBackground = Color(0xFF000000)
val LightSurface = Color(0xFFFFFFFF)
val OnLightSurface = Color(0xFF000000)
val LightSurfaceContainer = Color(0xFFBB86FC)
val OnLightSurfaceContainer = Color(0xFF000000)
val LightOutline = Color(0xFF6200EE)
val OnLightOutline = Color(0xFFFFFFFF)

// Dark theme colors
val DarkPrimary = Color(0xFFBB86FC)
val OnDarkPrimary = Color(0xFF000000)
val DarkPrimaryContainer = Color(0xFF3700B3)
val OnDarkPrimaryContainer = Color(0xFFFFFFFF)
val DarkSecondary = Color(0xFF03DAC6)
val OnDarkSecondary = Color(0xFF000000)
val DarkSecondaryContainer = Color(0xFF018786)
val OnDarkSecondaryContainer = Color(0xFFFFFFFF)
val DarkTertiary = Color(0xFF03DAC6)
val OnDarkTertiary = Color(0xFF000000)
val DarkTertiaryContainer = Color(0xFF018786)
val OnDarkTertiaryContainer = Color(0xFFFFFFFF)
val DarkError = Color(0xFFCF6679)
val OnDarkError = Color(0xFF000000)
val DarkErrorContainer = Color(0xFFB00020)
val OnDarkErrorContainer = Color(0xFFFFFFFF)
val DarkBackground = Color(0xFF121212)
val OnDarkBackground = Color(0xFFFFFFFF)
val DarkSurface = Color(0xFF121212)
val OnDarkSurface = Color(0xFFFFFFFF)
val DarkSurfaceContainer = Color(0xFF3700B3)
val OnDarkSurfaceContainer = Color(0xFFFFFFFF)
val DarkOutline = Color(0xFFBB86FC)
val OnDarkOutline = Color(0xFF000000)
